### ISSUE TITLE
anything happend

### ISSUE THREAD

**Issue by albertog** [google/streamy-dart#166]
when in run app to generate lib not happend anything only show again and again the paremeters message but not error, not messages and of course not generate lib anything. I do not what solve problemn.

casa bin # ./dart /home/albertog/streamy-dart/bin/apigen.dart --client-file-name=aa.dart --discovery-file=urlshortener.json --output-dir=url

-c, --client-file-name          Prefix for the .dart files generated.
-d, --discovery-file            Path to the discovery file.
-o, --output-dir                Directory for the generated client library package.
-a, --addendum-file             Path to addendum to the discovery file.
-t, --templates-dir             Directory containing code templates.
                                (defaults to "templates")

-v, --package-version           Version to be specified in the generated pubspec.yaml
                                (defaults to "0.0.0")

    --local-streamy-location    Path to a local Streamy package. If specified the local version will be used instead of pub version.

**Comment by alxhub** [comment]
Obsolete - predates YAML configs.
